theme = "github_dark"

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"
end-of-line-diagnostics = "error"

[editor.auto-save]
focus-lost = true
"after-delay.enable" = true

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
